### PR TITLE
fix(dev): resets Absolute Stroke Width

### LINKED ISSUE #2984: On HomeSite abolutestrokewidth does not reset
### Browser

- [x] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [x] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

When I am looking at the demo on the Home site, although everything else resets, absolutestrokewidth does not so when I was playing with it it took me a second to realize why I was getting much bolder icons because I assumed that it had reset.

When I click on reset:

Image

I can also open a fix for this, if it is determined to be neccesary.

### Steps to reproduce

1. Go to https://lucide.dev/
2. Scroll to Style as you please
3. Change stoke width and size
4. Toggle to enable absolute
5. Press the reset button

### Checklist

- [x] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

### PR DESCRIPTION
**Pull request by briz123**
closes #2984

## What is the purpose of this pull request?

- [ ] New Icon
- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other:

### Description

On the lucide website the reset button does not also reset the absolute stroke width. This change makes sure that the toggle resets.

## Before Submitting 

- [x] I've read the [Contribution Guidelines](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).
- [x] I've checked if there was an existing PR that solves the same issue.

### CODE REVIEW

File: docs/.vitepress/theme/components/icons/SidebarIconCustomizer.vue [hunk 1]
```diff
@@ -47,6 +47,10 @@ function resetStyle () {
   color.value = STYLE_DEFAULTS.color
   strokeWidth.value = STYLE_DEFAULTS.strokeWidth
   size.value = STYLE_DEFAULTS.size
+  absoluteStrokeWidth.value = STYLE_DEFAULTS.absoluteStrokeWidth
+  nextTick(() => {
+    
+  });
```
Comment (ericfennis) [inline docs/.vitepress/theme/components/icons/SidebarIconCustomizer.vue:53]: Shouldn't this be inside the nextTick function?
```suggestion
  nextTick(() => {
    absoluteStrokeWidth.value = STYLE_DEFAULTS.absoluteStrokeWidth
  });
```

File: docs/.vitepress/theme/components/home/HomeIconCustomizer.vue [hunk 2]
```diff
@@ -48,10 +48,16 @@ function resetStyle () {
   color.value = 'currentColor'
   strokeWidth.value = 2
   size.value = 24
+  absoluteStrokeWidth.value = false;
+  nextTick(() => {
+    
+  });
+
```
Comment (ericfennis) [inline docs/.vitepress/theme/components/home/HomeIconCustomizer.vue:55]: Should this not be in the nextTick function?
```suggestion
  nextTick(() => {
    absoluteStrokeWidth.value = false;
  });

```

Comment (briz123) [reply docs/.vitepress/theme/components/home/HomeIconCustomizer.vue]: On further reflection I think I may not have needed to include nextTick in the first place. Sorry this is my first time using Vue. I updated the branch accordingly and again thank you for helping me on this.

**Comment by briz123** [comment]
I removed the nextTick function as it doesn't add functionality in this case and it looks like everything works well. The reset button now resets absolute stroke width as well.

**Review by ericfennis — APPROVED** [review]
Awesome!

**Comment by epifaniofrancisco** [comment]
Could someone explain the reason for the revert? Was there an issue caused by the original changes, or something else that prompted this decision?
